#!/bin/bash
. test/integration/helper

setup () {
  true
}

assert_json () {
ruby -rjson -e '
  expected=JSON.load(ARGV[0])
  actual=JSON.load(STDIN.read)
  if expected == actual
    exit 0
  else
    STDERR.puts "#{expected.to_json} not equal to\n#{actual.to_json}"
    exit 1
  end
' "$@"
}

example () {
  printf "$PWD/examples/%s.rb" "$@"
}

test_jsonapi_generate_prints_payload_for_resource () {
jsonapi-generate "$(example persons)" | assert_json '
{
  "data": {
    "type": "persons",
    "attributes": {
      "first_name": "Sylvan",
      "last_name": "Bradtke",
      "gender": "female",
      "phones": [
        {
          "label": "home",
          "phone_number": "1-576-881-6778 x15989"
        }
      ],
      "address": {
        "street": "40350 Alexanne Vista",
        "city": "South Dimitri",
        "state": "Maryland"
      }
    }
  }
}'
}

#
# --attributes-only
#

test_jsonapi_generate_attributes_only_prints_attributes_for_resource () {
jsonapi-generate --attributes-only "$(example persons)" | assert_json '
{
  "first_name": "Sylvan",
  "last_name": "Bradtke",
  "gender": "female",
  "phones": [
    {
      "label": "home",
      "phone_number": "1-576-881-6778 x15989"
    }
  ],
  "address": {
    "street": "40350 Alexanne Vista",
    "city": "South Dimitri",
    "state": "Maryland"
  }
}'
}

#
# -h
#

test_jsonapi_generate_h_prints_help () {
jsonapi-generate -h | grep -q "usage: jsonapi-generate"
}

#
# -l
#

test_jsonapi_generate_l_maximizes_lists () {
jsonapi-generate -l max "$(example persons)" | jq -r .data.attributes.phones[].phone_number | assert_output "\
893.524.7688
1-878-159-8943
(123) 813-3370
"
}

test_jsonapi_generate_l_minimizes_lists () {
jsonapi-generate -l min "$(example persons)" | jq -r .data.attributes.phones[].phone_number | assert_output "\
893.524.7688
"
}
#
# -n
#

test_jsonapi_generate_n_specifies_how_many_payloads_to_emit () {
jsonapi-generate -n 3 "$(example persons)" | jq -r .data.attributes.first_name | assert_output "\
Sylvan
Wilson
Gilbert
"
}

. ts
